FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y --no-install-recommends python3-pip && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements-worker.txt .
RUN pip3 install --no-cache-dir -r requirements-worker.txt
COPY app app
COPY static static
ENV HF_HOME=/models
EXPOSE 8001
CMD ["uvicorn", "app.worker:app", "--host", "0.0.0.0", "--port", "8001"]
